config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

end

app/models/message.rb
class Message < ActiveRecord::Base
  belongs_to :conversation
  belongs_to :user

  validates_presence_of :content, :conversation_id, :user_id

  def message_time
  	created_at.strftime("%v")
  end

end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController
	before_action :authenticate_user!
	before_action :set_conversation

	def index
		if current_user == @conversation.sender || current_user == @conversation.recipient
			@other = current_user == @conversation.sender ? @conversation.recipient : @conversation.sender
			@messages = @conversation.messages.order("created_at DESC")
		else
			redirect_to conversations_path, alert: "You don't have permission to view this."
		end
	end

	def create
		@message = @conversation.messages.new(message_params)
		@messages = @conversation.messages.order("created_at DESC")

		if @message.save
			respond_to do |format|
				format.js
			end
		end
	end

	private

		def set_conversation
			@conversation = Conversation.find(params[:conversation_id])
		end

		def message_params
			params.require(:message).permit(:content, :user_id)
		end
end

app/views/messages/_message.html.erb
<div class="panel">
	<div class="panel-body">
		<%= image_tag avatar_url(message.user), class: "img-circle avatar-small" %>
		<strong><%= message.user.fullname %></strong>

		<span class="pull-right"><%= message.message_time %></span>
		<br>
		<div class="row-space-2">
			<%= message.content %>
		</div>
	</div>
</div>

app/views/messages/create.js.erb
<% publish_to conversation_messages_path(@conversation) do %>
	$('#chat').prepend("<%= j render @message %>");
<% end %>

$('#new_message')[0].reset();

app/views/messages/index.html.erb
<div class="row">
	
	<div class="col-md-3 text-center">
		<%= image_tag avatar_url(@other), class: "img-circle avatar-medium" %><br>
		<strong><%= @other.fullname %></strong>
		<%= link_to "View Profile", @other, class: "btn btn-default wide" %>
	</div>

	<div class="col-md-9">
		
		<div class="panel panel-default">
			<div class="panel-heading">
				Conversation with <%= @other.fullname %>
			</div>
			<div class="panel-body">
				<div class="container">
					
					<%= form_for [@conversation, @conversation.messages.new], remote: true do |f| %>
						<div class="form-group">
							<%= f.text_area :content, placeholder: "Add a personal message", class: "form-control" %>
						</div>
						<%= f.hidden_field :user_id, value: current_user.id %>

						<div class="actions">
							<%= f.submit "Send Message", class: "btn btn-primary" %>
						</div>
					<% end %>

				</div>
			</div>
		</div>

		<div id="chat">
			<%= render @messages, locals: {conversation: @conversation} %>
		</div>

	</div>

</div>

<%= subscribe_to conversation_messages_path(@conversation) %>