config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

end

app/views/shared/_devisemes.html.erb
<% unless resource.errors.empty? %>
	<script type="text/javascript">
		<% resource.errors.full_messages.each do |msg| %>
			toastr.error('<%= msg %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_message.html.erb
<% unless flash.empty? %>
	<script type="text/javascript">
		<% flash.each do |f| %>
			<% type = f[0].to_s.gsub('alert','error').gsub('notice','info') %>
			toastr['<%= type %>']('<%= f[1] %>')
		<% end %>
	</script>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Static navbar -->
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="#">AirAlien</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">

      <%= form_tag search_path, class: "navbar-form navbar-left", method: :get do %>
        <div class="form-group">
          <%= text_field_tag :search, params[:search], placeholder: "Where are you going?", class: "form-control" %>
        </div>
      <% end %>

      <ul class="nav navbar-nav navbar-right">
        
        <% if(!user_signed_in?) %>
          <li><%= link_to "Log In", new_user_session_path %></li>
          <li><%= link_to "Sign Up", new_user_registration_path %></li>
        <% else %>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">
              <%= image_tag avatar_url(current_user), class: "img-circle avatar-small" %>&nbsp;
              <%= current_user.fullname %> <span class="caret"></span>
            </a>

            <ul class="dropdown-menu">
              <li><%= link_to "Your Listings", rooms_path %></li>
              <li><%= link_to "Your Reservations", your_reservations_path %></li>
              <li><%= link_to "Your Trips", your_trips_path %></li>
              <li><a href="#">Wish Lists</a></li>
              <li><%= link_to "Edit Profile", edit_user_registration_path %></li>
              <li role="separator" class="divider"></li>
              <li><a href="#">Account Setting</a></li>
              <li><%= link_to "Log out", destroy_user_session_path, method: :delete %></li>
            </ul>
          </li>
        <% end %>

        <li>
          <%= link_to conversations_path do %>
            <i class="fa fa-envelope-o"></i> Messages
          <% end %>
        </li>
        <li>
          <%= link_to new_room_path do %>
            <i class="fa fa-home fa-lg"></i> Become a Host
          <% end %>
        </li>

        
      </ul>
      
    </div><!--/.nav-collapse -->
  </div>
</nav>