config/routes.rb
Rails.application.routes.draw do

  root 'pages#home'

  devise_for 	:users, 
  						:path => '', 
  						:path_names => {:sign_in => 'login', :sign_out => 'logout', :edit => 'profile'},
  						:controllers => {:omniauth_callbacks => 'omniauth_callbacks',
  														 :registrations => 'registrations'
  														}

  resources :users, only: [:show]
  resources :rooms
  resources :photos

  resources :rooms do
    resources :reservations, only: [:create]
  end

  resources :conversations, only: [:index, :create] do
    resources :messages, only: [:index, :create]
  end

  resources :rooms do
    resources :reviews, only: [:create, :destroy]
  end

  get '/preload' => 'reservations#preload'
  get '/preview' => 'reservations#preview'

  get '/your_trips' => 'reservations#your_trips'
  get '/your_reservations' => 'reservations#your_reservations'

  post '/notify' => 'reservations#notify'
  post '/your_trips' => 'reservations#your_trips'

  get '/search' => 'pages#search'

end

app/models/reservation.rb
class Reservation < ActiveRecord::Base
  belongs_to :user
  belongs_to :room
end

app/controllers/reservations_controller.rb
class ReservationsController < ApplicationController
	before_action :authenticate_user!, except: [:notify]

	def preload
		room = Room.find(params[:room_id])
		today = Date.today
		reservations = room.reservations.where("start_date >= ? OR end_date >= ?", today, today)

		render json: reservations	
	end

	def preview
		start_date = Date.parse(params[:start_date])
		end_date = Date.parse(params[:end_date])

		output = {
			conflict: is_conflict(start_date, end_date)
		}

		render json: output
	end

	def create
		@reservation = current_user.reservations.create(reservation_params)

		if @reservation
			# send request to PayPal
			values = {
				business: 'demo.code4startup-facilitator@gmail.com',
				cmd: '_xclick',
				upload: 1,
				notify_url: 'http://22ee1588.ngrok.io/notify',
				amount: @reservation.total,
				item_name: @reservation.room.listing_name,
				item_number: @reservation.id,
				quantity: '1',
				return: 'http://22ee1588.ngrok.io/your_trips'
			}

			redirect_to "https://www.sandbox.paypal.com/cgi-bin/webscr?" + values.to_query
		else
			redirect_to @reservation.room, alert: "Oops, something went wrong..."
		end 
	end

	protect_from_forgery except: [:notify]
	def notify
		params.permit!
		status = params[:payment_status]

		reservation = Reservation.find(params[:item_number])

		if status = "Completed"
			reservation.update_attributes status: true
		else
			reservation.destroy
		end

		render nothing: true
	end

	protect_from_forgery except: [:your_trips]
	def your_trips
		@trips = current_user.reservations.where("status = ?", true)
	end

	def your_reservations
		@rooms = current_user.rooms
	end

	private
		def is_conflict(start_date, end_date)
			room = Room.find(params[:room_id])

			check = room.reservations.where("? < start_date AND end_date < ?", start_date, end_date)
			check.size > 0? true : false
		end

		def reservation_params
			params.require(:reservation).permit(:start_date, :end_date, :price, :total, :room_id)
		end
end

app/views/reservations/_form.html.erb
<%= form_for([@room, @room.reservations.new]) do |f| %>
	
	<div class="row">
		<div class="col-md-12 price_tag">
			<span>$<%= @room.price %></span>
			<span class="pull-right">Per Night</span>
		</div>
	</div>

	<div class="row">
		<div class="col-md-6">
			<label>Check In</label>
			<%= f.text_field :start_date, readonly: 'true', placeholder: 'Start Date', class: 'form-control' %>		
		</div>
		<div class="col-md-6">
			<label>Check Out</label>
			<%= f.text_field :end_date, readonly: 'true', placeholder: 'End Date', class: 'form-control', disabled: 'true' %>		
		</div>
	</div>

	<%= f.hidden_field :room_id, value: @room.id %>
	<%= f.hidden_field :price, value: @room.price %>
	<%= f.hidden_field :total, id: 'reservation_total' %>

	
	<h4><span id="message"></span></h4>

	<div id="preview" style="display: none">
		<table class="reservation-table" >
			<tbody>
				<tr>
					<td>Day(s)</td>
					<td><span id="reservation_days"></span></td>
				</tr>
				<tr>
					<td>Total</td>
					<td>$<span id="reservation_sum"></span></td>
				</tr>
			</tbody>
		</table>
		<br>
	</div>
	
	<%= f.submit "Book Now", id: "btn_book", class: "btn btn-primary wide", disabled: 'true' %>
	
<% end %>

<script>

	function unavailable(date) {
		dmy = date.getDate() + "-" + (date.getMonth()+1) + "-" + date.getFullYear();
		return [$.inArray(dmy, unavailableDates) == -1];
	}

	$(function() {

		unavailableDates = [];

		$.ajax({
			url: '/preload',
			data: {'room_id': <%= @room.id %>},
			dataType: 'json',
			success: function(data) {

				$.each(data, function(arrID, arrValue) {
					for(var d = new Date(arrValue.start_date); d <= new Date(arrValue.end_date); d.setDate(d.getDate() + 1)) {
						unavailableDates.push($.datepicker.formatDate('d-m-yy', d));
					}
				});

				$('#reservation_start_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#reservation_end_date').datepicker("option", "minDate", selected);
						$('#reservation_end_date').attr('disabled', false);

						var start_date = $(this).datepicker('getDate');
						var end_date = $('#reservation_end_date').datepicker('getDate');
						var days = (end_date - start_date)/1000/60/60/24 + 1

						var input = {
							'start_date': start_date,
							'end_date': end_date,
							'room_id': <%= @room.id %>
						}

						$.ajax({
							url: "/preview",
							data: input,
							success: function(data) {

								if (data.conflict) {

									$('#message').text("This date range is not available.");
									$('#preview').hide();
									$('#btn_book').attr('disabled', true);

								} else {

									$('#preview').show();
									$('#btn_book').attr('disabled', false);

									var total = days * <%= @room.price %>
									$('#reservation_days').text(days);
									$('#reservation_sum').text(total);
									$('#reservation_total').val(total);
								}
							}
						});
					}
				});

				$('#reservation_end_date').datepicker({
					dateFormat: 'dd-mm-yy',
					minDate: 0,
					maxDate: '3m',
					beforeShowDay: unavailable,
					onSelect: function(selected) {
						$('#reservation_start_date').datepicker("option", "maxDate", selected);

						var start_date = $('#reservation_start_date').datepicker('getDate');
						var end_date = $(this).datepicker('getDate');
						var days = (end_date - start_date)/1000/60/60/24 + 1

						var input = {
							'start_date': start_date,
							'end_date': end_date,
							'room_id': <%= @room.id %>
						}

						$.ajax({
							url: "/preview",
							data: input,
							success: function(data) {

								if (data.conflict) {

									$('#message').text("This date range is not available.");
									$('#preview').hide();
									$('#btn_book').attr('disabled', true);

								} else {

									$('#preview').show();
									$('#btn_book').attr('disabled', false);

									var total = days * <%= @room.price %>
									$('#reservation_days').text(days);
									$('#reservation_sum').text(total);
									$('#reservation_total').val(total);
								}
							}
						});

					}
				});
			}
		});

		

	});
</script>

app/views/reservations/your_reservations.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link active" %></li>
			<li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Reservations
			</div>
			<div class="panel-body">
				<% @rooms.each do |room| %>
					
					<% room.reservations.each do |reservation| %>
						<% if reservation.status %>
							<div class="row">
								<div class="col-md-2">
									<%= reservation.start_date.strftime('%v') %>
								</div>	
								<div class="col-md-6">
									<%= link_to room_path(reservation.room) do %>
										<%= image_tag reservation.room.photos[0].image.url(:thumb) if reservation.room.photos.length > 0 %>
									<% end %>
								</div>	
								<div class="col-md-2">
									<%= link_to user_path(reservation.user) do %>
										<%= image_tag avatar_url(reservation.user), class: "img-circle avatar-medium" %>
									<% end %>	
								</div>	
								<div class="col-md-2 right">
									<h4>$<%= reservation.total %></h4>
								</div>	
							</div>
							<hr>
						<% end %>
					<% end %>

				<% end %>

			</div>
		</div>
	</div>
</div>

app/views/reservations/your_trips.html.erb
<div class="row">
	<div class="col-md-3">
		<ul class="sidebar-list">
			<li class="sidebar-item"><%= link_to "Your Listing", rooms_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Reservations", your_reservations_path, class: "sidebar-link" %></li>
			<li class="sidebar-item"><%= link_to "Your Trips", your_trips_path, class: "sidebar-link active" %></li>
		</ul>
	</div>
	<div class="col-md-9">
		<div class="panel panel-default">
			<div class="panel-heading">
				Your Trips
			</div>
			<div class="panel-body">
				
				<% @trips.each do |trip| %>
					<div class="row">
						<div class="col-md-2">
							<%= trip.start_date.strftime('%v') %>
						</div>	
						<div class="col-md-6">
							<%= link_to room_path(trip.room) do %>
								<%= image_tag trip.room.photos[0].image.url(:thumb) if trip.room.photos.length > 0 %>
							<% end %>
						</div>	
						<div class="col-md-2">
							<%= link_to user_path(trip.room.user) do %>
								<%= image_tag avatar_url(trip.room.user), class: "img-circle avatar-medium" %>
							<% end %>	
						</div>	
						<div class="col-md-2 right">
							<h4>$<%= trip.total %></h4>
						</div>	
					</div>
					<hr>
				<% end %>

			</div>
		</div>
	</div>
</div>